// The design system's icon names mapped to Lucide icons (same style: line icons on a 24px grid).
import {
  Calendar,
  Captions,
  Check,
  ChevronRight,
  Clock,
  Copy,
  Ellipsis,
  Hand,
  House,
  Link,
  Lock,
  MessageSquare,
  Mic,
  MicOff,
  Monitor,
  Moon,
  PhoneOff,
  Plus,
  ScreenShare,
  Search,
  Send,
  Signal,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Ticket,
  Users,
  Video,
  VideoOff,
  X,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  mic: Mic,
  "mic-off": MicOff,
  camera: Video,
  "camera-off": VideoOff,
  screen: ScreenShare,
  chat: MessageSquare,
  hand: Hand,
  leave: PhoneOff,
  users: Users,
  captions: Captions,
  more: Ellipsis,
  sparkle: Sparkles,
  check: Check,
  close: X,
  send: Send,
  lock: Lock,
  signal: Signal,
  sliders: SlidersHorizontal,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  home: House,
  calendar: Calendar,
  search: Search,
  plus: Plus,
  clock: Clock,
  link: Link,
  ticket: Ticket,
  copy: Copy,
  chevron: ChevronRight,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
export const ICON_NAMES = Object.keys(ICONS) as IconName[];
